server:
  port: 9002

#jsp
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/shop/
#      suffix: .jsp
  devtools:
    livereload:
      enabled: true
#naver
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 0a7JFA6L_oFY2Quv_yOH
            client-secret: FCV3Rw7ZtL
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,nickname,email,profile_image
            client-name: Naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

#mysql
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul
   username: root
   password: gmltn1234^

  servlet:
    multipart:
      max-file-size: 10MB
    
#type을 data.*로 해도 다됨!
mybatis:
  type-aliases-package: data.mapper,data.dto
  mapper-locations:
  - /mapper/**/*.xml

